### ISSUE TITLE
Erweiterung Schnittstelle HealthCheck (group_health)

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#232]
Die Projektgruppe HealthCheck arbeitet an einer Erweiterung und braucht dafür zwei Anpassungen an der Schnittstelle:

### Opt-In und Daten der Kantonalverbände und Regionen (Prio 1)

- Opt-in ebenfalls für KVs und Regionen ermöglichen (Checkbox im GUI einbauen)
![grafik](https://user-images.githubusercontent.com/1799621/186665939-de4399cf-a473-43a9-bf20-75e52990bca9.png)

Queries / Schnittstelle anpassen
- Personen und Rollen der KVs und Regionen sollen in der Schnittstelle mitgeliefert werden (ev. keine Änderung nötig)
  - Dies soll weiterhin in Abhängigkeit zum Opt-in der jeweiligen Ebene stehen
- Es sollen auch Gremien und Kommissionen in den Queries aufgenommen werden (ev. bereits der Fall)
- Interne Gremien sollen aus allen Queries ausgeschlossen werden
- See https://github.com/hitobito/hitobito_pbs/blob/master/app/controllers/group_health_controller.rb

### API für Statstik (Prio 2)

- Neuer API-Endpunkt für die Statstik erstellen
  - Beispiel https://db.scout.ch/de/groups/4438/census/abteilung.json
- Neue Berechtigung "Statstik" fürs API (auf allen Ebenen inkl. Bundesebene).
  - Nur Service Tokens auf Bundesebene dürfen diese Berechtigung bekommen
- Daten analog GUI (Stufen,m,w,Total) ausgeben
- Daten aller Jahre liefern oder Get-Parameter fürs Jahr einbauen

## Technisches
Innerhalb hitobito ist die Schnittstelle mit group_health zu finden.
Umsetzung im PBS Wagon

## TODO
**Prio 1**
- [x] Attribut `:group_health` auf `Kantonalverband` und `Region` zu den `self.used_attributes` hinzufügen, analog wie es bereits auf Abteilung der Fall ist
- [x] In den Endpoints `people`, `roles`, `groups`, `courses`, `camps`, `participations`, `qualifications` und optional `group_types` interne Gremien in den SQL Queries ausschliessen. Entweder in jedem Endpoint einzeln oder falls eine generische Lösung möglich ist.
- [x] Ggf. bestehende Tests anpassen
- [x] Neue Tests schreiben für das Verhalten mit den internen Gremien

**Prio 2**
- [x] Im `GroupHealthController` einen neuen Endpoint `census_evaluations` erstellen (und Route dafür erstellen)
- [x] Der Endpoint soll (wie alle anderen auch) nur Daten von Abteilungen, Regionen und Kantonen lieferen, welche den **Opt-In aktiviert haben** (wird in den bisherigen Endpoints via `GROUP_HEALTH_JOIN` sichergestellt)
- [x] Der Endpoint soll vorerst nur die Daten des Partials `app/views/census_evaluation/base/_total_row` liefern (nicht die Aufteilung nach Untergruppen wie sie z.B. auf Kantonen im UI erscheint)
- [x] Mit einem GET-Parameter `year` wird gesteuert, aus welchem Jahr die Daten exportiert werden
- [x] Die Daten sollen in einem sinnvollen JSON-Format geliefert werden. Z.B. ein Objekt mit den Keys `f`, `m`, `total`, und darin je Objekte mit den Keys aus `MemberCount::COUNT_CATEGORIES` und entsprechendenen numerischen Values.
- [x] Auf `Pbs::ServiceToken` neues Boolean-Feld `census_evaluations`, welches analog zu `group_health` nur auf dem Top Layer aktiviert sein darf
- [x] Neuen Scope `census_evaluations` ungefähr analog zum Commit 720e3b4f60566a3b190a1b3dc6898725719e8389 im PBS-Wagon einbauen
- [x] Im neuen `census_evaluations`-Endpoint muss zusätzlich zur `:show, GroupHealthController` Berechtigung auch noch die neue `census_evaluations` Berechtigung der Service Tokens vorhanden sein
