### ISSUE TITLE
Anpassung der Kursrollen an die SportDB

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito_pbs#233]
Anpassung für die PBS: 
 - Kursteam und Referent\*in bei der Vergabe der Qualifikationen inkludieren

Vermutlich erst für den [NDS Export](https://github.com/hitobito/hitobito/issues/1733) relevant:
- Referent\*in als "Drittperson" in der NDS matchen
---

Ursprüngliche Anforderung aus der PBS-Ausbildung:

> Künftig hätten wir gerne folgende Rollen:
>
> **Kursleiter\*in**
> Anerkennungen werden verlängert (gemäss Kursart-Einstellungen für Kursteam)
> 
> **Klassenlehrer\*in**
> Anerkennungen werden verlängert (gemäss Kursart-Einstellungen für Kursteam)
> 
> **Kursteam (Drittperson)**
> Anerkennungen werden verlängert (gemäss Kursart-Einstellungen für Kursteam)
> 
> **Referent\*in (Drittperson)**
> Anerkennungen werden verlängert (gemäss Kursart-Einstellungen für Kursteam)
> 
> **Küche**
> KEINE Verlängerung von Anerkennungen

## TODO
Umsetzung im PBS Wagon

- [ ] Anpassung analog zu https://github.com/hitobito/hitobito_jubla/pull/38 im PBS Wagon umsetzen (die Rolle bei der PBS heisst Referent*in statt Helfer*in, kurz in den Übersetzungen nachschauen welche Event::Role das ist)
- [ ] Changelog-Eintrag im PBS-Wagon machen
- [ ] Mit angemessener Rolle durchklicken

**Comment by ThomasEllenberger** [comment]
Wir haben diese Anpassung für die Rolle "Helfer*in" jetzt gerade für die Jubla im Core umgesetzt. Ich ging davon aus, dies sei mit der Pfadi und Cevi so abgesprochen.
https://github.com/hitobito/hitobito_jubla/issues/33

Vermutlich könnte man dies relativ einfach auf die weiteren Rollen ausweiten. 
Könnte man dies denn im Core umsetzen? So dass man nach dem Kurs sämtliche Rollen sieht und ihnen die Anerkennung geben kann? (Dann könnte jeder selbst entscheiden wem er die Anerkennung gibt und wem nicht, hätte aber die Möglichkeit dies allen Rollen zu vergeben.)
Wäre dies für euch denkbar @richardjubla und @nchiapol?

**Comment by richardjubla** [comment]
Nach interner Rücksprache kann ich folgendes ergänzen:

> Eine Absprache zwischen Pfadi, Cevi, Jubla fand im Mai/Juni durch die Ausbildungsverantwortlichen statt - jedoch war die Schlussfolgerung damals, dass die Anpassung wohl einzeln eingegeben werden müssen, weil pro Verband die Rollen in den Kursen bereits jetzt unterschiedlich heissen und funktionieren. Deshalb haben Jubla und Pfadi unterschiedliche Tickets eröffnet. Wenn trotzdem etwas übernommen werden kann, dann umso besser.
> Dass man im Kurs bei Klick auf "Qualifikationen" alle Rollen sieht und alle Quali vergeben kann ist insofern ungünstig, da die Fehleranfälligkeit (Qualivergabe an Küche, an Personen die weniger als 6h Kadertätigkeit ausüben) erhöht wird.

**Comment by Michael-Schaer** [comment]
Ich würde den letzten Satz von @richardjubla unterstützen: Der Prozess sollte so sein, dass möglichst wenig Fehler passieren.

Ich denke, die wichtigste Änderung ist, dass die PBS Anerkennungen für die Rolle "Referent*in" vergeben will. Bzw. dass wir diese ebenfalls als "Drittperson" in der NDS matchen.

@ThomasEllenberger: Vielleicht ist es das einfachste, diese einzelne Rolle im PBS-Wagon anzupassen?
