### ISSUE TITLE
Erweiterung group_health - Anpassung API-Schnittstelle

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_pbs#241]
In Issue #232 wurde der neue API Endoint für den group_health Check definiert.

Nach dem Testen sind der PBS noch zwei Probleme mit der API für Statistik aufgefallen:

1. Der Endpoint soll Daten sämtlicher Abteilungen liefern, nicht nur derer welche das Opt-In aktiviert haben.
Aktuell können die Statistik Daten auf Abteilungen auch von Personen eingesehen werden, welche keine Rolle auf der Gruppe oder einer übergeordneten Gruppe haben. Aus diesem Grund wird hier kein Bruch in der Ansichtsberechtigung gesehen.

2. Die API für die Statistik soll Berechtigungsmässig unabhängig von der Health Check APi sein. API's mit der Berechtigung "Bestandesmeldung Export-Endpunkt" sollen unabhängig von der Berechtigung "HealthCheck Export-Endpunkt" funktionieren.

# ToDo

- [x] `GroupHealthzController#census_evaluation` anpassen
- [x] Einschränkung auf `group_health: true` entfernen
- [x] Ability für group_health und census_evaluation sollen unabhängig voneinander sein (`TokenAbility`)
- [x] Specs anpassen
- [ ] Mit angemessenem Token abfragen

**Comment by Michael-Schaer** [comment]
Merci fürs Spezifizieren. Was mir noch aufgefallen ist: In der Produktion sehe ich eine Berechtigung, die schon ziemlich nach Bestandesmeldung klingt:

![grafik](https://user-images.githubusercontent.com/1799621/201688520-e2b15792-bb1b-42e6-80a6-f6861e859579.png)

Ich frage mich, ob diese doch bereits umgesetzt wurde, oder - wenn nein - ob sie für das Vorhaben verwendet werden könnte. Schaut das doch noch mal gut an...
