### ISSUE TITLE
PEOPLE: Aufzeigen welche Personen Zugriff auf meine Daten haben

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_pbs#257]
es soll in Hitobito aufgezeigt werden, welche anderen Rollen Zugriff auf meine Daten haben. (Daten des aktuell eingeloggten Users/Person)

Mit https://github.com/hitobito/hitobito_pbs/pull/196 wurde ein erster PoC dazu erstellt.

* Es werden vorerst einfach Gruppen und Rollen mit Zugriff aufgelistet (nicht welche Personen effektiv Zugriff haben)
* Platzierung auf dem Tab 'Sicherheit' in neuem Abschnitt und nicht auf der Hilfeseite wie im PR

# Tech-Spec

- Umsetzung im Core
- Muss die Performance für diesen Request optimiert werden? Schlussendlich scheint es eine gute Idee einfach über alle Rollen zu iterieren und dann einen Permission check mit can? zu machen. Das deckt sicher alle Rollen ab. (Diesen Punkt einfach noch prüfen, gibt es Performance Probleme so?) Daten für diesen Abschnitt ggf. nur Laden wenn Collapsed wird?

# Todo

- [x] PR auf aktuellen Master rebasen
- [x] Inhalt nach Sicherheitstab des eigenen Profils verschieben
- [x] Performance Thema mit einem PBS Prod db dump testen
- [x] Specs ergänzen
- [ ] Kunde wegen Übersetzungen informieren
- [x] Workflow von Anfang bis Ende "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
So wie ich das sehe: 

- Siehe Antwort von Michael: Vorerst nur Gruppen und Rollen
- Wenn wir Prio zwei in der offerierten Zeit umsetzen können finde ich das auch sinnvoll, dass man auf allen Personen  sehen kann, wer auf die jeweilige Person Zugriff hat, nicht nur auf sich selbst.
- Ich finde die Platzierung im "Sicherheit" Tab sehr gut. 1. gehört das meines Erachtens zum Thema Sicherheit, 2. Ich finde es intuitiv dies dort zu suchen, 3. Damit ist auch gleich gewährleistet, dass dies nur sehen kann wer aufs Sicherheitstab dieser Person Zugriff hat.
- Denke auch, dass dies für andere Organisationen interesant sein könnte, allerdings wohl nur für solche bei denen sich die Mitglieder auch selbst einloggen. Deshalb: Wenn Umsetzung im Core, dann mit Featuretoggle und nur falls dies in der offerierten Zeit umsetzbar ist. (@Michael-Schaer Das wäre evtl etwas was wir gleich noch ans Community Meeting mitnehmen könnten?)
- Ich denke es wäre schön, wenn diese Liste gleich so wie sie ist im "Sicherheit" Tab ersichtlich ist. Falls dies aber zuviel performance braucht, dann Umsetzung mit einem Link auf eine separate Seite, welche dann diese Informationen sammelt und anzeigt.

**Comment by Michael-Schaer** [comment]
Merci für die Klärung. Ich bin einverstanden, dass wir diese erste Version einfach halten.

>"Zugriff auf meine Daten" ist also aktuell so zu verstehen, dass man meine Adresse, Telefonnummern, und Informationen im Abschnitt "Weitere Angaben" sehen kann, aber nicht unbedingt meine Rollen, Tags, Qualifikationen, Notizen, etc.

Ich werde die Release-Notes entsprechend formulieren.

**Comment by Michael-Schaer** [comment]
@ThomasEllenberger @mtnstar 

Beim Testen erhalte ich eine Zeitüberschreitung:
![grafik](https://github.com/hitobito/hitobito_pbs/assets/1799621/6ab1ce80-0dad-4174-94ff-6d6c40d05a06)

Hier scheint etwas noch nicht zu stimmen.

**Comment by ThomasEllenberger** [comment]
Hey @Michael-Schaer 

Konnte das bei mir auch nachstellen.
Bei meinen Tests hatte es bei allen Personen funktioniert, und auch jetzt bei einem erneuten Test funktioniert es bei allen Personen welche ich ausprobiere, ausser bei Hussein Kohlmann. Dieser hat enorm viele Rollen. Vermute dass es daran liegen könnte.

@mtnstar  & @TheWalkingLeek könnt ihr euch das evtl. nochmals anschauen?

**Comment by Michael-Schaer** [comment]
Wenn das Timeout für den Call vergrössert werden kann, wäre das sicher gut. Wenn es aber für Personen mit 15-20 Rollen geht, passt es für mich.

**Comment by TheWalkingLeek** [comment]
@Michael-Schaer wir haben das Timeout auf der Integration auf 3 Minuten gehoben, wie auch schon bei der Prod.
Die Abfrage ging bei mir jetzt ca. 43 Sekunden, ich hoffe daher dass es ausreichen sollte :)

**Comment by Michael-Schaer** [comment]
Super, merci, jetzt klappt es!

**Comment by richardjubla** [comment]
> @richardjubla Merci für den Tipp, das auch gelöschte Gruppen vorkommen. @ThomasEllenberger Ist das ein Fehler, oder hat das eine Absicht dahinter?
> 
> @richardjubla Was meinst du damit, dass Profile sich gegenseitig sehen können? [hitobito/hitobito#1688 (comment)](https://github.com/hitobito/hitobito/pull/1688#issuecomment-1604187824)

@Michael-Schaer 

Das gelöschte Gruppen vorkommen, ist aus meiner aktuellen Sicht ein "Feature". Dies weil die gelöschten Gruppen ihre Berechtigungen und insbesondere die ContactData-Flag/Kontaktrelevanz behalten. In unserem Wagon ist das so. 
Demzufolge sehen sich zum Beispiel auch Profile, welche die Kontaktrelevanz aus einer gelöschten Gruppe erhalten. 

Ob Profile mit der Löschung einer Gruppe ihre Rechte/Kontaktrelevanz verlieren sollen/müssen kann ich aktuell nicht beurteilen. Bei unserem Wagon kommt hinzu, dass der Ehemaligen-Status (Ehemalige Rollen) weiterhin aktive Berechtigungen und  ContactData-Flag/Kontaktrelevanz geben.

**Comment by ThomasEllenberger** [comment]
@Michael-Schaer So wie ich dass sehe wurde das Feature so konzipiert, dass alle Personen/Rollen welche show:details haben aufgelistet bleiben. 
Wenn Rollen in gelöschten Gruppen diese Berechtigung behalten ist dies meiner Meinung nach korrekt, dass diese weiterhin aufgelistet bleiben.

Dieses Feature wurde mit dem heutigen Release auf eure Produktivumgebugen gespielt. Ich gehe davon aus, dass dieses abgeschlossen ist. Sind hier Änderungen gewünscht, oder soll dieses (für eine spezifische Umgebung oder den Core) noch weiter entwickelt werden, bitte ich auch, erneut auf mich zu zu kommen.
