### ISSUE TITLE
Silverscouts: Eigener Root-Knoten

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_pbs#271]
refs #235

Um die Silverscouts besser von der bestehenden Struktur der PBS abzugrenzen, sollen sie einen eigenen Root-Knoten erhalten. Dabei soll die URL db.scout.ch weiterhin auf Pfadibewegung Schweiz zeigen. Die URL sisc.scout.ch soll hingegen auf die neue Silverscouts-Struktur zeigen.

Innerhalb der Silverscouts gibt es den Gruppentyp "Region". Eine Region hat folgende Rollen:

Mitglied
Leiter*in (mit Contact Data)
Achtung: Mitglieder sehen sich nicht gegenseitig! Sie sehen aber Leiter*innen der gleichen Region. Dies soll auch beim Export beachtet werden.

Leiter*innen sehen und bearbeiten alle Personen in der Region und haben ein Contact Data Flag.

Aktive und Ehemaligen können sich also nur via ihrer Leiter*innen vernetzen (welche ein Contact Data Flag haben). Bei Events ist es ok, wenn sich Aktive und Ehemalige gegenseitig sehen können. Ansonsten bleiben die Ebenen Silverscouts und Pfadibewegung Schweiz getrennt, Personen sehen sich gegenseitig nicht.

# Offene Fragen

- Braucht es Anpassungen an
    - Statistiken
    - Exports

# TODO

Anpassungen in PBS Wagon

- [x] Neues root Layer anlegen, darin Rolle "Admin" mit 
    ```
        self.permissions = [:layer_and_below_full]
        self.two_factor_authentication_enforced = true
    ```
- [x] `Group::Bund` als child dem neuen root Layer anhängen 
- [x] Neues Layer `Group::Silverscouts` erstellen und als child dem root Layer anhängen
- [x] Rolle `Group::Silverscouts::Leitung` mit `self.permissions = [:group_read, :contact_data]`
- [x] Rolle `Group::Silverscouts::Mitglied`
- [x] Manuell Testen
- [x] Der Rolle "Admin" auf der neuen Root-Gruppe auch noch `:admin` Permission vergeben
- [x] Neue Gruppe `Group::Silverscouts::Region` erstellen und als child dem `Group::Silverscouts` Layer anhängen. Die Region muss selber keine Sub-Regionen unterstützen (also keine children).
- [x] Die oben genannten Rollen `Group::Silverscouts::Leitung` und `Group::Silverscouts::Mitglied` müssen in der Silverscouts-Region verfügbar sein, nicht auf der `Group::Silverscouts`. Daher werden sie nachher `Group::Silverscouts::Region::Mitglied` bzw. `Group::Silverscouts::Region::Leitung` heissen
- [x] Auf dem Silverscouts-Dachverband `Group::Silverscouts` sollen folgende Rollen verfügbar sein:
  - [x] Rolle Verantwortliche\*r mit Permissions `:layer_and_below_full`
  - [x] Rolle Lesezugriff mit Permissions `:layer_and_below_read`
  - [x] Rolle PowerUser mit Permissions `:layer_full`
- [ ] Kunde für Überseztungen informieren
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
@Michael-Schaer gemäss aktueller Tech-Spezifikation und Implementation würden sämtliche SilverScouts-Mitglieder in ein und derselben Gruppe "Silverscouts" direkt unter dem neuen Root-Knoten landen. Ich glaube aber (basierend auf den Erklärungen in https://github.com/hitobito/hitobito_pbs/issues/273) es braucht Silverscouts-Regionen, oder? Wie sollen diese Regionen verschachtelbar sein? Mein Vorschlag:
```
Root
  Silverscouts (neue "Schwestergruppe" der PBS. Welche Rollen sind hier nötig?)
    Silverscouts Region X (enthält Mitglieder und Leitungsrollen)
    Silverscouts Region Y (enthält Mitglieder und Leitungsrollen)
```

Braucht es auch Unter-Regionen? Also dass Region X noch weitere Untergruppen enthalten kann? Wenn ja, sollen diese Unter-Regionen, falls sie Selbstregistrierung aktiviert haben, ebenfalls im automatischen Ehemaligen-Einladungs-Mail aufgelistet werden?

**Comment by Michael-Schaer** [comment]
@carlobeltrame Ja, Regionen muss es unbedingt geben. Diese heissen zum Beispiel "Romandie", "Innerschweiz" oder "Aargau & Solothurn".

Verschachteln ist nicht nötig und muss im E-Mail nicht beachtet werden.

**Comment by carlobeltrame** [comment]
@Michael-Schaer und welche Rollen sollen auf der "schweizweiten" Silverscouts-Gruppe verfügbar sein? Auf dem bisherigen PBS-Dachverband gibts ja diverse Rollen, z.B. Mitarbeiter\*in GS, IT-Support, etc.
