### ISSUE TITLE
Silverscouts: Domains auf bestimmte Gruppen zeigen lassen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_pbs#272]
refs #235 

Die URL https://db.scout.ch weiterhin auf Pfadibewegung Schweiz zeigen. Die URL https://sisc.scout.ch soll hingegen auf die neue Silverscouts-Struktur zeigen.
Dafür müssen die Gruppen erweitert werden, dass ein Hostname hinterlegt werden kann.

Im SBV Wagon ist diese Funktionalität bereits implementiert:
https://github.com/hitobito/hitobito_sbv/commit/34a92c6

# ToDo

Anpassungen in PBS Wagon

- [ ] Column `groups.hostname` und Validierungen hinzufügen analog SBV
- [ ] Group Edit view ergänzen um Group#hostname editierbar zu machen für Gruppen welche direkt am root layer hängen
- [ ] Manuell Testen
- [ ] Kunde für Überseztungen informieren
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
Für all deine Fragen ist die Antwort die von dir präferierte.
Beim Logo können wir für die neue Superstruktur das bisherige SVG-Logo belassen, aber bei den SilverScouts ein eigenes PNG-Logo hochladen. Dann müsste es weiterhin so funktionieren wie gewünscht.
