### ISSUE TITLE
PERSON: Benutzerdaten-Minimierung PBS

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_pbs#300]
Mit Issue #2106 wurde die Möglichkeit zur Datenminimierung geschaffen.

Die PBS hat nun definiert welche Daten bei einer Minimierung in ihrem Wagon gelöscht und welche beibehalten werden sollen:

Es wird gelöscht:
- Tags
- Notizen
- Adresse
- Weitere E-Mails
- Telefonnummern
- Social Media
- Titel
- Anrede
- Sprache
- Schulklasse
- Eintritt / Austritt
- J+S Personennummer (sowieso nicht mehr relevant in der MiData)
- Nationalität J+S
- Geschwister
- Zusätzliche Angaben
- Foto

Im Umkehrschluss wird folgendes beibehalten:
- Vorname
- Pfadiname
- Geschlecht
- Geburtsdatum
- Haupt-E-Mail (selber seine Daten bearbeiten können)
- AHV-Nummer (Löschen wir in Zusammenhang mit einem anderen Ticket, soll hier nicht Thema sein)
- Rollen und Event-Teilnahmen
- Abos
- Rechnungen
- Verlauf, Log (Version 1 mal sein lassen und Erfahrungen sammeln?)
- Status Login / Sperrung

## Tech-Spec

- Umsetzung im PBS Wagon
- Nur diejenigen Tags sollen gelöscht werden, welche in den [SubscriptionTags.excluded](https://github.com/hitobito/hitobito/blob/master/app/models/subscription_tag.rb) der *aktuellen* Abos der Person nicht verwendet werden

## ToDo

- [x] [People::Minimizer](https://github.com/hitobito/hitobito/blob/master/app/domain/people/minimizer.rb) im PBS Wagon prependen
  - [x] In der Methode `minimize` die Felder gemäss Spezifikation löschen
- [x] Nur diejenigen Tags sollen gelöscht werden, welche in den [SubscriptionTags.excluded](https://github.com/hitobito/hitobito/blob/master/app/models/subscription_tag.rb) der **aktuellen** Abos der Person nicht verwendet werden. Konkret vor der Löschung der Tags folgendes ausführen:
  - [x] Alle MailingLists der Person auflisten mit [Person::Subscriptions](https://github.com/hitobito/hitobito/blob/master/app/domain/person/subscriptions.rb#L7)
  - [x] In all diesen MailingLists die SubscriptionTags.excluded heraussuchen
  - [x] Auf der Person nur die Tags löschen, die in keinem dieser SubscriptionTags referenziert werden
- [x] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken" (die Frage ist, wie?)
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by Michael-Schaer** [comment]
Danke für den Hinweis! Wenn das Löschen eines Tags dazu führt, dass die Person Teil einer Zielgruppe wird, wäre das aus meiner Sicht recht unschön. Wäre es möglich, solche Fälle zu verhindern? Falls das weitere Probleme verursacht, tendiere ich aktuell dazu, die Tags bei der Minimierung zu ignorieren.

Die Person sowieso aus allen Abos zu entfernen, wäre auch eine mögliche Interpretation der Minimierung. Damit würde ich aber lieber noch warten, bis wir ein paar Erfahrungen mit der Funktion haben.

**Comment by carlobeltrame** [comment]
> Wäre es möglich, solche Fälle zu verhindern?

Ja, es wäre möglich, nur diejenigen Tags zu löschen welche beim Zeitpunkt der Minimierung nicht in einem Abo zur Filterung (Nur Personen mit einem der folgenden Tags auswählen / Ausschliessen von Personen mit folgenden Tags) verwendet werden. Je nach detaillierter Ausgestaltung könnte das mehr oder weniger kompliziert werden, aber es wäre grundsätzlich möglich.

Wenn wir aber einige der Tags auf der Person belassen, können diese Tags natürlich in Zukunft auch bei neuen Abos weiter verwendet werden. Beispielsweise wenn jemand das Tag "Interessiert an Seiltechnik" bei der Minimierung behält, weil es ein Abteilungs-Abo gibt welches dieses Tag verwendet, dann könnte später ein kantonales Seiltechnik-Abo auch nach diesem Tag filtern und die minimierte Person wieder finden.
Falls du das meinst mit "dass die Person Teil einer Zielgruppe wird", dann sehe ich keinen Weg das zu verhindern. Dann müsstest du mir fachlich sagen wie du dir das Verhalten vorstellst.

**Comment by Michael-Schaer** [comment]
@carlobeltrame Nein, ich meine den Fall, in dem das Löschen eines Tags aktiv dazu führt, dass eine Person bei der Minimierung in eine Zielgruppe fällt. Es geht mir also nur um die Option "Ausschliessen von Personen mit folgenden Tags" im Abo.

Situation, die zu verhindern ist:
- Abo XY schliesst Personen mit Tag ABC aus
- Person meldet sich für eine Datenlöschung
- Es ist nur eine Minimierung möglich, wegen vorherigen Kurs-/Lagerbesuchen
- Die Person wird minimiert und verliert den Tag ABC
- Die Person landet damit neu in der Zielgruppe des Abos XY
- Die Person bekommt zwei Tage später ein Mail mit Betreff "Aufruf an unsere Gönner"

Die Person wollte eine Datenlöschung und erhält jetzt stattdessen wieder Mails von uns 🙃👎

**Comment by carlobeltrame** [comment]
Ja, dann habe ich dich richtig verstanden. Es ist machbar, nur die Tags zu löschen die aktuell in keinem Abo zum Ausschluss führen. Das bedeutet aber definitiv einen Mehraufwand. Wenn euch das bewusst ist, kann ich das so spezifizieren.
