### ISSUE TITLE
Einladung in Modal öffnen

### ISSUE THREAD

**Issue by samuelsteiner** [hitobito/hitobito_pbs#331]
Als eingeladener User
soll die im Mail verlinkte Einladung in einem Modal öffnen,
damit ich sie besser sehe (aktuell fast nicht erkennbar).

# Mockup

Die entspr. Funktionalität soll in einem Modal geöffnet werden, wenn ich über den im E-Mail eingebetteten Link komme.
![CleanShot 2024-06-03 at 14 53 43](https://github.com/hitobito/hitobito_pbs/assets/4127782/6016024a-35c3-4959-9683-a5c798984118)

# ToDo

- [ ] Modal
- [ ] Anpassung Link in E-Mail
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
