### ISSUE TITLE
MAILS: Neuer Mailtitel für Silverscouts Versand

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_pbs#334]
Für die PBS wurden neue custom content mails für die Silverscouts anmeldungen erstellt.
(Ich vermute durch https://github.com/hitobito/hitobito_pbs/issues/273)
Die Bezeichnung dieser Mails sind aktuell wie folgt: 
![grafik](https://github.com/hitobito/hitobito_pbs/assets/100761305/3ec811de-6df4-46cf-8137-145cdfd506c1)

Die Bezeichnungen dieser Mails soll angepasst werden.
Neu sollen diese wie folgt heissen:

Alt: Ehemalige Einladungsmail ohne Silverscouts -> Neu: Ehemalige Einladungsmail: Nur Silverscout-Gruppen
Alt: Ehemalige Erinnerungsmail ohne Silverscouts -> Neu: Ehemalige Erinnerungsmail: Nur Silverscout-Gruppen

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [x] Migration erstellen
- [x] Domainklasse erstellen oder anpassen
- [x] Model/View/Controller anpassen
- [x] Neues Feature mit FeatureGate deaktivierbar machen
- [x] Specs schreiben
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
