### ISSUE TITLE
API: Schnittstelle Pfadistiftung zu Sisc-Datenbank

### ISSUE THREAD

**Issue by yvesflueck** [hitobito/hitobito_pbs#347]
Um die Daten bei der Pfadistiftung mit den Daten in der Silverscouts-Datenbank synchron halten zu können, wird eine entsprechende Schnittstelle benötigt.
Diese Schnittstelle soll einen Zeitstempel annehmen und dann von allen Personen im Silverscouts-Baum Daten herausgeben, welche seit dem gegebenen Zeitpunkt geändert wurden. Konkret geht es hier um die folgenden Daten, die exportiert werden sollten:
- Adresse mit Strasse, PLZ, Ort, Land
- Ablaufdatum auf einer Rolle in der Silverscouts-Gruppe
- Haupt-E-Mail
- Pfadiname
- Anrede
- Sprache
- Geburtsdatum

Hier möchten wir gerne, dass nur Daten anschliessend ausgegeben werden, die auch seit dem erwähnten Zeitpunkt verändert wurden. Alle anderen Daten, die nicht verändert wurden, werden auch nicht ausgegeben.

Könnte evtl. auch mit der bestehenden API umgesetzt werden, aber müsste man noch abklären.

# Tech-Spec

- Eine neue API-Schnittsstelle ist erreichbar, an welche man einen Zeitstempel mitgeben kann.
- Der API-Aufruf gibt die oben genannten Daten aller Personen im Silverscouts-Stamm zurück, sofern diese seit dem angegebenen Zeitpunkt verändert wurden

# ToDo

- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by yvesflueck** [comment]
@ellenberger Kannst du bitte dieses Feature noch einschätzen und mir ein entsprechendes Angebot zukommen lassen.
